server:
  error:
    whitelabel:
      enabled: false
    include-message: always
  port: 8090

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  jackson:
    serialization:
      fail-on-empty-beans: false
    time-zone: Brazil/East
    locale: pt_BR

springdoc:
  swagger-ui:
    path: /swagger.html # http://localhost:8090/swagger.html
  api-docs:
    path: /api-docs # http://localhost:8090/api-docs
    enabled: true
